version: '4.30.0'

services:

  mongo:
    image: mongo
    container_name: project_api_mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345

  mongo-express:
    image: mongo-express
    container_name: project_api_mongo_express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://root:12345@mongo:27017/
      ME_CONFIG_BASICAUTH: false
